FROM node:22-alpine

WORKDIR /app

# Copy le repertoire front user (donc .) dans le repertoire courant du conteneur (donc .)
COPY . .

# Telecharge les dependences
RUN npm install

CMD ["npm", "run", "dev"]