name: Test and build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Use Node.js 21
        uses: actions/setup-node@v4
          with:
            node-version: 21
            cache: 'npm'
      - name: Installation des dependances
        run: npm ci
      - name: Verification code JS
        run: npm run lint
      - name: Build du package
        run: npm run build      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/polytech2024
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: rg.fr-par.scw.cloud/polytech-2024/vremy/frontend:v1
